spring:
  application:
    name: banco-digital-api
  profiles:
    active: dev
  mail:
    host: smtp.gmail.com
    port: 587
    username: banco.digital.borriguel.dev@gmail.com
    password: mtdjrpdbksvhatqa
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
